spring:
  application:
    name: insight
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: news-module-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

news:
  crawler:
    max-items: 20
    cron: "0 0 12 * * *"

gemini:
  api-key:
  model: gemini-1.5-flash

discussion:
  service:
    url: http://localhost:8080
