spring:
  config:
    import:
      - optional:classpath:application-kafka.yml
      - optional:classpath:application-oauth.yml

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

logging:
  level:
    root: info
    depth.finvibe.investment: info
springdoc:
  swagger-ui:
    path: /doc/insight/swagger-ui.html
  api-docs:
    path: /doc/insight/v3/api-docs


security:
  jwt:
    hmac-secret: ${JWT_SECRET}

market:
  service:
    url: ${MARKET_SERVICE_URL:http://finvibe.space}
  category:
    service:
      url: ${MARKET_CATEGORY_SERVICE_URL:http://investment}

langchain4j:
  google-ai-gemini:
    chat-model:
      api-key: ${GEMINI_API_KEY}
      model-name: gemini-3-flash-preview
