spring:
  profiles:
    active: local
  web:
    resources:
      add-mappings: false

  application:
    name: insight

news:
  crawler:
    max-items: 20
    cron: "0 0 0 * * *"

gemini:
  api-key: ${GEMINI_API_KEY:}
  model: gemini-1.5-flash

discussion:
  service:
    url: http://localhost:8080

springdoc:
  swagger-ui:
    path: /doc/user/swagger-ui.html
  api-docs:
    path: /doc/user/v3/api-docs

resilience4j:
  circuitbreaker:
    instances:
      discussionServiceCount:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      discussionServiceCounts:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      discussionServiceList:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
